version: '3.9'

services:
  mongo_db:
    container_name: mongo_database
    image: mongo:latest
    restart: always
    ports:
      - 2727:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_VOLUMES_HOST_PATH}:/data/db

  node_api:
    container_name: node_api
    build:
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo_db
